# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageMixer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1457, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Image1Comp = QtWidgets.QComboBox(self.layoutWidget)
        self.Image1Comp.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Image1Comp.setFont(font)
        self.Image1Comp.setEditable(False)
        self.Image1Comp.setObjectName("Image1Comp")
        self.Image1Comp.addItem("")
        self.Image1Comp.addItem("")
        self.Image1Comp.addItem("")
        self.Image1Comp.addItem("")
        self.horizontalLayout_2.addWidget(self.Image1Comp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.Image1 = ImageView(self.frame)
        self.Image1.setObjectName("Image1")
        self.gridLayout.addWidget(self.Image1, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Image1Component = ImageView(self.frame_2)
        self.Image1Component.setObjectName("Image1Component")
        self.gridLayout_2.addWidget(self.Image1Component, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.Image2Comp = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.Image2Comp.setFont(font)
        self.Image2Comp.setObjectName("Image2Comp")
        self.Image2Comp.addItem("")
        self.Image2Comp.addItem("")
        self.Image2Comp.addItem("")
        self.Image2Comp.addItem("")
        self.horizontalLayout_4.addWidget(self.Image2Comp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Image2 = ImageView(self.frame_3)
        self.Image2.setObjectName("Image2")
        self.gridLayout_3.addWidget(self.Image2, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Image2Component = ImageView(self.frame_4)
        self.Image2Component.setObjectName("Image2Component")
        self.gridLayout_4.addWidget(self.Image2Component, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line = QtWidgets.QFrame(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.OutPut_Box = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.OutPut_Box.setFont(font)
        self.OutPut_Box.setObjectName("OutPut_Box")
        self.OutPut_Box.addItem("")
        self.OutPut_Box.addItem("")
        self.horizontalLayout_6.addWidget(self.OutPut_Box)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setVerticalSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Component1Box = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.Component1Box.setFont(font)
        self.Component1Box.setObjectName("Component1Box")
        self.Component1Box.addItem("")
        self.Component1Box.setItemText(0, "")
        self.Component1Box.addItem("")
        self.Component1Box.addItem("")
        self.Component1Box.addItem("")
        self.Component1Box.addItem("")
        self.Component1Box.addItem("")
        self.Component1Box.addItem("")
        self.gridLayout_7.addWidget(self.Component1Box, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Slider1 = QtWidgets.QSlider(self.layoutWidget2)
        self.Slider1.setMaximum(100)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName("Slider1")
        self.verticalLayout_3.addWidget(self.Slider1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.showValue1 = QtWidgets.QLabel(self.layoutWidget2)
        self.showValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.showValue1.setObjectName("showValue1")
        self.horizontalLayout_7.addWidget(self.showValue1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.Image1ComboBox = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.Image1ComboBox.setFont(font)
        self.Image1ComboBox.setObjectName("Image1ComboBox")
        self.Image1ComboBox.addItem("")
        self.Image1ComboBox.addItem("")
        self.gridLayout_7.addWidget(self.Image1ComboBox, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setVerticalSpacing(10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 0, 1, 1)
        self.Component2Box = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.Component2Box.setFont(font)
        self.Component2Box.setObjectName("Component2Box")
        self.Component2Box.addItem("")
        self.Component2Box.setItemText(0, "")
        self.Component2Box.addItem("")
        self.Component2Box.addItem("")
        self.Component2Box.addItem("")
        self.Component2Box.addItem("")
        self.Component2Box.addItem("")
        self.Component2Box.addItem("")
        self.gridLayout_11.addWidget(self.Component2Box, 0, 1, 1, 1)
        self.Image2ComboBox = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.Image2ComboBox.setFont(font)
        self.Image2ComboBox.setObjectName("Image2ComboBox")
        self.Image2ComboBox.addItem("")
        self.Image2ComboBox.addItem("")
        self.gridLayout_11.addWidget(self.Image2ComboBox, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Slider2 = QtWidgets.QSlider(self.layoutWidget2)
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setObjectName("Slider2")
        self.verticalLayout_4.addWidget(self.Slider2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.showValue2 = QtWidgets.QLabel(self.layoutWidget2)
        self.showValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.showValue2.setObjectName("showValue2")
        self.horizontalLayout_10.addWidget(self.showValue2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.gridLayout_11.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_11)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_5.addWidget(self.line_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.frame_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Output1 = ImageView(self.frame_5)
        self.Output1.setObjectName("Output1")
        self.gridLayout_6.addWidget(self.Output1, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.frame_7 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Output2 = ImageView(self.frame_7)
        self.Output2.setObjectName("Output2")
        self.gridLayout_10.addWidget(self.Output2, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1457, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionsave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Image1"))
        self.Image1Comp.setCurrentText(_translate("MainWindow", "Magnitude Spectral"))
        self.Image1Comp.setItemText(0, _translate("MainWindow", "Magnitude Spectral"))
        self.Image1Comp.setItemText(1, _translate("MainWindow", "Phase Spectral"))
        self.Image1Comp.setItemText(2, _translate("MainWindow", "Real Component"))
        self.Image1Comp.setItemText(3, _translate("MainWindow", "Imaginary Component"))
        self.label_4.setText(_translate("MainWindow", "Image2"))
        self.Image2Comp.setCurrentText(_translate("MainWindow", "Magnitude Spectral"))
        self.Image2Comp.setItemText(0, _translate("MainWindow", "Magnitude Spectral"))
        self.Image2Comp.setItemText(1, _translate("MainWindow", "Phase Spectral"))
        self.Image2Comp.setItemText(2, _translate("MainWindow", "Real Component"))
        self.Image2Comp.setItemText(3, _translate("MainWindow", "Imaginary Component"))
        self.label_5.setText(_translate("MainWindow", "Mixer OutPut"))
        self.OutPut_Box.setItemText(0, _translate("MainWindow", "OutPut_1"))
        self.OutPut_Box.setItemText(1, _translate("MainWindow", "OutPut_2"))
        self.Component1Box.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.Component1Box.setItemText(2, _translate("MainWindow", "Uniform Magnitude"))
        self.Component1Box.setItemText(3, _translate("MainWindow", "Phase"))
        self.Component1Box.setItemText(4, _translate("MainWindow", "Uniform Phase"))
        self.Component1Box.setItemText(5, _translate("MainWindow", "Real"))
        self.Component1Box.setItemText(6, _translate("MainWindow", "Imaginary"))
        self.label_12.setText(_translate("MainWindow", "Component_1"))
        self.label.setText(_translate("MainWindow", "0%"))
        self.showValue1.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "100%"))
        self.Image1ComboBox.setItemText(0, _translate("MainWindow", "Image_1"))
        self.Image1ComboBox.setItemText(1, _translate("MainWindow", "Image_2"))
        self.label_14.setText(_translate("MainWindow", "Component_2"))
        self.Component2Box.setItemText(1, _translate("MainWindow", "Phase"))
        self.Component2Box.setItemText(2, _translate("MainWindow", "Magnitude"))
        self.Component2Box.setItemText(3, _translate("MainWindow", "Uniform Magnitude"))
        self.Component2Box.setItemText(4, _translate("MainWindow", "Uniform Phase"))
        self.Component2Box.setItemText(5, _translate("MainWindow", "Real"))
        self.Component2Box.setItemText(6, _translate("MainWindow", "Imaginary"))
        self.Image2ComboBox.setItemText(0, _translate("MainWindow", "Image_1"))
        self.Image2ComboBox.setItemText(1, _translate("MainWindow", "Image_2"))
        self.label_6.setText(_translate("MainWindow", "0%"))
        self.showValue2.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "100%"))
        self.label_11.setText(_translate("MainWindow", "OutPut_1"))
        self.label_13.setText(_translate("MainWindow", "OutPut_2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open "))
        self.actionsave.setText(_translate("MainWindow", "save"))
from pyqtgraph import ImageView
