# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Equalizer1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Signal_Status = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Signal_Status.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        self.Signal_Status.setFont(font)
        self.Signal_Status.setObjectName("Signal_Status")
        self.verticalLayout_3.addWidget(self.Signal_Status)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(481, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1665, 500))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.channel1 = PlotWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel1.sizePolicy().hasHeightForWidth())
        self.channel1.setSizePolicy(sizePolicy)
        self.channel1.setMinimumSize(QtCore.QSize(300, 104))
        self.channel1.setObjectName("channel1")
        self.verticalLayout.addWidget(self.channel1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.channel2 = PlotWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel2.sizePolicy().hasHeightForWidth())
        self.channel2.setSizePolicy(sizePolicy)
        self.channel2.setMinimumSize(QtCore.QSize(300, 104))
        self.channel2.setObjectName("channel2")
        self.verticalLayout.addWidget(self.channel2)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.channel3 = PlotWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel3.sizePolicy().hasHeightForWidth())
        self.channel3.setSizePolicy(sizePolicy)
        self.channel3.setMinimumSize(QtCore.QSize(300, 104))
        self.channel3.setObjectName("channel3")
        self.verticalLayout.addWidget(self.channel3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.channel4 = PlotWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel4.sizePolicy().hasHeightForWidth())
        self.channel4.setSizePolicy(sizePolicy)
        self.channel4.setMinimumSize(QtCore.QSize(300, 104))
        self.channel4.setObjectName("channel4")
        self.verticalLayout.addWidget(self.channel4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEffects = QtWidgets.QMenu(self.menuBar)
        self.menuEffects.setObjectName("menuEffects")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../New folder (2)/task1-team_18/Images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_File.setIcon(icon)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../New folder (2)/task1-team_18/Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_File.setIcon(icon1)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionEqualization = QtWidgets.QAction(MainWindow)
        self.actionEqualization.setObjectName("actionEqualization")
        self.actionRectangular = QtWidgets.QAction(MainWindow)
        self.actionRectangular.setObjectName("actionRectangular")
        self.actionHamming = QtWidgets.QAction(MainWindow)
        self.actionHamming.setObjectName("actionHamming")
        self.actionHanning = QtWidgets.QAction(MainWindow)
        self.actionHanning.setObjectName("actionHanning")
        self.actionFFT_Input = QtWidgets.QAction(MainWindow)
        self.actionFFT_Input.setObjectName("actionFFT_Input")
        self.actionFFT_Output = QtWidgets.QAction(MainWindow)
        self.actionFFT_Output.setObjectName("actionFFT_Output")
        self.actionDifference = QtWidgets.QAction(MainWindow)
        self.actionDifference.setObjectName("actionDifference")
        self.actionFFT_Difference = QtWidgets.QAction(MainWindow)
        self.actionFFT_Difference.setObjectName("actionFFT_Difference")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../New folder (2)/task1-team_18/Images/play2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon2)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../New folder (2)/task1-team_18/Images/Stop1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../New folder (2)/task1-team_18/Images/pause2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon4)
        self.actionPause.setObjectName("actionPause")
        self.actionOriginal_Signal = QtWidgets.QAction(MainWindow)
        self.actionOriginal_Signal.setObjectName("actionOriginal_Signal")
        self.actionOutPut_Signal = QtWidgets.QAction(MainWindow)
        self.actionOutPut_Signal.setObjectName("actionOutPut_Signal")
        self.actionDifference_Signal = QtWidgets.QAction(MainWindow)
        self.actionDifference_Signal.setObjectName("actionDifference_Signal")
        self.actionFFT_Original = QtWidgets.QAction(MainWindow)
        self.actionFFT_Original.setObjectName("actionFFT_Original")
        self.actionFFT_OutPut = QtWidgets.QAction(MainWindow)
        self.actionFFT_OutPut.setObjectName("actionFFT_OutPut")
        self.actionFFT_Difference_2 = QtWidgets.QAction(MainWindow)
        self.actionFFT_Difference_2.setObjectName("actionFFT_Difference_2")
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionPause)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave_File)
        self.menuEffects.addAction(self.actionEqualization)
        self.menuView.addAction(self.actionOutPut_Signal)
        self.menuView.addAction(self.actionDifference_Signal)
        self.menuView.addAction(self.actionFFT_Original)
        self.menuView.addAction(self.actionFFT_OutPut)
        self.menuView.addAction(self.actionFFT_Difference_2)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEffects.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Signal_Status.setText(_translate("MainWindow", "                                                        Signal Graph"))
        self.label.setText(_translate("MainWindow", "                                                                                       Input Signal "))
        self.label_2.setText(_translate("MainWindow", "                                                                                    FFT Input Signal                                                                                                          "))
        self.label_4.setText(_translate("MainWindow", "                                                                                       Output Signal "))
        self.label_5.setText(_translate("MainWindow", "                                                                                   FFT Output Signal"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEffects.setTitle(_translate("MainWindow", "Effects"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))
        self.actionSave_File.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionEqualization.setText(_translate("MainWindow", "Equalization"))
        self.actionEqualization.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionRectangular.setText(_translate("MainWindow", "Rectangular"))
        self.actionHamming.setText(_translate("MainWindow", "Hamming"))
        self.actionHanning.setText(_translate("MainWindow", "Hanning"))
        self.actionFFT_Input.setText(_translate("MainWindow", "FFT (Input)"))
        self.actionFFT_Output.setText(_translate("MainWindow", "FFT (Output)"))
        self.actionDifference.setText(_translate("MainWindow", "Difference "))
        self.actionFFT_Difference.setText(_translate("MainWindow", "FFT (Difference)"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Ctrl+Media Play"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setShortcut(_translate("MainWindow", "Ctrl+Media Stop"))
        self.actionOriginal_Signal.setText(_translate("MainWindow", "Original Signal"))
        self.actionOutPut_Signal.setText(_translate("MainWindow", "OutPut Signal"))
        self.actionDifference_Signal.setText(_translate("MainWindow", "Difference Signal"))
        self.actionFFT_Original.setText(_translate("MainWindow", "FFT Original"))
        self.actionFFT_OutPut.setText(_translate("MainWindow", "FFT (OutPut)"))
        self.actionFFT_Difference_2.setText(_translate("MainWindow", "FFT (Difference)"))

from pyqtgraph import PlotWidget
