# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sliders2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 454)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Slider1 = QtWidgets.QSlider(Form)
        self.Slider1.setMinimum(-20)
        self.Slider1.setMaximum(20)
        self.Slider1.setPageStep(5)
        self.Slider1.setProperty("value", 1)
        self.Slider1.setOrientation(QtCore.Qt.Vertical)
        self.Slider1.setObjectName("Slider1")
        self.horizontalLayout.addWidget(self.Slider1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Slider2 = QtWidgets.QSlider(Form)
        self.Slider2.setMinimum(-20)
        self.Slider2.setMaximum(20)
        self.Slider2.setPageStep(5)
        self.Slider2.setProperty("value", 1)
        self.Slider2.setOrientation(QtCore.Qt.Vertical)
        self.Slider2.setObjectName("Slider2")
        self.horizontalLayout.addWidget(self.Slider2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.Slider3 = QtWidgets.QSlider(Form)
        self.Slider3.setMinimum(-20)
        self.Slider3.setMaximum(20)
        self.Slider3.setPageStep(5)
        self.Slider3.setProperty("value", 1)
        self.Slider3.setOrientation(QtCore.Qt.Vertical)
        self.Slider3.setObjectName("Slider3")
        self.horizontalLayout.addWidget(self.Slider3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.Slider4 = QtWidgets.QSlider(Form)
        self.Slider4.setMinimum(-20)
        self.Slider4.setMaximum(20)
        self.Slider4.setPageStep(5)
        self.Slider4.setProperty("value", 1)
        self.Slider4.setOrientation(QtCore.Qt.Vertical)
        self.Slider4.setObjectName("Slider4")
        self.horizontalLayout.addWidget(self.Slider4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.Slider5 = QtWidgets.QSlider(Form)
        self.Slider5.setMinimum(-20)
        self.Slider5.setMaximum(20)
        self.Slider5.setPageStep(5)
        self.Slider5.setProperty("value", 1)
        self.Slider5.setOrientation(QtCore.Qt.Vertical)
        self.Slider5.setObjectName("Slider5")
        self.horizontalLayout.addWidget(self.Slider5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.Slider6 = QtWidgets.QSlider(Form)
        self.Slider6.setMinimum(-20)
        self.Slider6.setMaximum(20)
        self.Slider6.setPageStep(5)
        self.Slider6.setProperty("value", 1)
        self.Slider6.setOrientation(QtCore.Qt.Vertical)
        self.Slider6.setObjectName("Slider6")
        self.horizontalLayout.addWidget(self.Slider6)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.Slider7 = QtWidgets.QSlider(Form)
        self.Slider7.setMinimum(-20)
        self.Slider7.setMaximum(20)
        self.Slider7.setPageStep(5)
        self.Slider7.setProperty("value", 1)
        self.Slider7.setOrientation(QtCore.Qt.Vertical)
        self.Slider7.setObjectName("Slider7")
        self.horizontalLayout.addWidget(self.Slider7)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.Slider8 = QtWidgets.QSlider(Form)
        self.Slider8.setMinimum(-20)
        self.Slider8.setMaximum(20)
        self.Slider8.setPageStep(5)
        self.Slider8.setProperty("value", 1)
        self.Slider8.setOrientation(QtCore.Qt.Vertical)
        self.Slider8.setObjectName("Slider8")
        self.horizontalLayout.addWidget(self.Slider8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.Slider9 = QtWidgets.QSlider(Form)
        self.Slider9.setMinimum(-20)
        self.Slider9.setMaximum(20)
        self.Slider9.setPageStep(5)
        self.Slider9.setProperty("value", 1)
        self.Slider9.setOrientation(QtCore.Qt.Vertical)
        self.Slider9.setObjectName("Slider9")
        self.horizontalLayout.addWidget(self.Slider9)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.Slider10 = QtWidgets.QSlider(Form)
        self.Slider10.setMinimum(-20)
        self.Slider10.setMaximum(20)
        self.Slider10.setPageStep(5)
        self.Slider10.setProperty("value", 1)
        self.Slider10.setOrientation(QtCore.Qt.Vertical)
        self.Slider10.setObjectName("Slider10")
        self.horizontalLayout.addWidget(self.Slider10)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.view_edit = PlotWidget(Form)
        self.view_edit.setObjectName("view_edit")
        self.verticalLayout_3.addWidget(self.view_edit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rectangular = QtWidgets.QRadioButton(Form)
        self.rectangular.setObjectName("rectangular")
        self.verticalLayout_2.addWidget(self.rectangular)
        self.hamming = QtWidgets.QRadioButton(Form)
        self.hamming.setObjectName("hamming")
        self.verticalLayout_2.addWidget(self.hamming)
        self.hanning = QtWidgets.QRadioButton(Form)
        self.hanning.setObjectName("hanning")
        self.verticalLayout_2.addWidget(self.hanning)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.play_btn = QtWidgets.QPushButton(Form)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_4.addWidget(self.play_btn)
        self.stop_btn = QtWidgets.QPushButton(Form)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_4.addWidget(self.stop_btn)
        self.reset_btn = QtWidgets.QPushButton(Form)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_4.addWidget(self.reset_btn)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_4.addWidget(self.save_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_12.setText(_translate("Form", " 20 dB"))
        self.label_13.setText(_translate("Form", "   1 dB"))
        self.label_14.setText(_translate("Form", " -20 dB"))
        self.rectangular.setText(_translate("Form", "Rectangular"))
        self.hamming.setText(_translate("Form", "Hamming"))
        self.hanning.setText(_translate("Form", "Hanning"))
        self.play_btn.setText(_translate("Form", "Play"))
        self.stop_btn.setText(_translate("Form", "Stop"))
        self.reset_btn.setText(_translate("Form", "Reset"))
        self.save_btn.setText(_translate("Form", "Save"))

from pyqtgraph import PlotWidget
